language: perl

install:
  - sudo apt-get update
  - sudo apt-get install libarchive-dev
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version Test::Vars || true
  - cpanm Alien::Libarchive::Installer -n
  - cpanm -n FFI::Raw || true
  - cpanm -n Test::CChecker

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"

env:
  - ALIEN_LIBARCHIVE=share
  - ALIEN_LIBARCHIVE=system

#before_script: /bin/true

script: dzil test -v

#after_script: /bin/true
